### ISSUE TITLE
Looks like debug code is active in Steam version (other are not tested)

### ISSUE THREAD

**Issue by krypt-lynx** [fluffy-mods/DesirePaths#9]
**Describe the bug**  
Looks like steam version of Desire Paths 0.8.102 permanently stuck in debug mode:
It draws red/green squares behind/under moving pawns
Older version are ok.

**Expected behavior**  
no debug info rendered

**Steps to reproduce**  
Install steam version of the mod

**Other mods**  
list of 50 of them, some of them are my own and is not published. Notable ones are:
- Dubs Bad Hygiene, 
- Hospitality
- Prison Labor
- Alien Races Framework

**Output log**  
no log

**Environment**  
 - OS: Win7 x64 Home Premium
 
**Game**
 - Steam, 1.1.2654 (64-bit)

**Comment by YotaXP** [comment]
Example of the overlay:
![image](https://user-images.githubusercontent.com/1637936/89496932-4b2db700-d789-11ea-8dde-e5d7135b5c86.png)
![image](https://user-images.githubusercontent.com/1637936/89505184-3a843d80-d797-11ea-95a5-43d83b2c899c.png)

Am also playing with several other mods.
